<?php

// This is a SPIP language file  --  Ceci est un fichier langue de SPIP nommé  genere le NOW()
// langue / language = en

$GLOBALS[$GLOBALS['idx_lang']] = array(


'activer'	=>	"put on sale"	,
'ajouter_categorie'	=>	"add a category"	,
'ajouter_logo'	=>	"add a picture"	,
'aucune_enchere'	=>	"no auction for the moment"	,

//	B		,
'telecharger_image'	=>	"download a picture"	,

//	C		,
'categorie_liste'	=>	"chosen categories"	,
'categorie_objet_choisis'	=>	"chosen categories"	,
'champ_obligatoire'	=>	" compulsory field"	,
'choisir_categories'	=>	"choose category"	,
'choisir_projet'	=>	"choose a project"	,
'choisir_region'	=>	"choose your province"	,
'choisir_type_auteur'	=>	"choose your type"	,
'choix_projets1'	=>	"first project preference"	,
'choix_projets2'	=>	"second project preference"	,
'choix_projets3'	=>	"third project preference"	,
'cloture_enchere'	=>	"the auction ends within"	,
'compte_bancaire'	=>	" bank account number"	,
'confirmer'	=>	"confirm"	,

//	D		,
'date_debut'	=>	"The auction is starting on…………………"	,
'date_debut_court'	=>	"starting date"	,
'date_fin'	=>	"ending date"	,
'deja'	=>	"already"	,
'desactiver'	=>	" put in stand by"	,
'descriptif'	=>	"description"	,
'donnees_objets'	=>	"detailed description"	,
'duree'	=>	"	",
'duree_valide'	=>	"please mention a valid duration",

//	E		,
'eliminer'	=>	"remove"	,
'email_asso_enchere_gagne_objet_message'	=>	"	",
'email_asso_enchere_gagne_sujet'	=>	"Item sold for your profit: payment to check"	,
'email_enchere_perdu_objet_message'	=>	"	",
'email_enchere_perdu_sujet'	=>	"item which hasn't been taken away"	,
'email_encherisseur_enchere_reussi_objet_message'	=>	"	",
'email_encherisseur_enchere_reussi_sujet'	=>	"successful auction"	,
'email_enchere_gagnee_message_paypal_asso'	=>	"The association also gives you the opportunity to effect your payment on its Paypal account"	,
'email_enchere_gagnee_message_paypal_kidonateur'	=>	"the kiddonor also gives you the opportunity to pay those costs via paypal"	,
'email_encherisseur_surpasse_sujet'	=>	"surpassed auction"	,
'email_encherisseur_surpasse_objet_message'	=>	"	",
'email_enchere_gagnee_message_specifique_venir'	=>	"	",
'email_enchere_gagnee_message_specifique_livraison'	=>	"	",
'email_enchere_gagnee_message_specifique_posteouvenir'	=>	"	",
'email_enchere_gagnee_sujet'	=>	"sale closure: the item has been taken away."	,
'email_enchere_gagnee_objet_message'	=>	"	",
'email_mise_vente_objet_message'	=>	"	",
'email_kidonateur_enchere_gagnee_message_specifique_livraison'	=>	"The buyer has also been given instruction for the payment of transport costs on your account"	,
'email_kidonateur_enchere_gagnee_message_specifique_posteouvenir'	=>	"If he wants to pick up the item, he will get in touch with you by e-mail"	,
'email_kidonateur_enchere_gagnee_message_specifique_venir'	=>	"You can e-mail the buyer to organize the taking-away of the item via his address"	,
'email_kidonateur_enchere_gagnee_objet_message'	=>	"	 ",
'email_kidonateur_enchere_gagnee_sujet'	=>	"closed sale. Your item has been sold"	,
'email_kidonateur_enchere_sansmise_objet_message'	=>	"	",
'email_kidonateur_enchere_sansmise_sujet'	=>	"unsold item : put on sale again,free of charge"	,
'email_paiement_ok_acheteur_message_specifique_venir'	=>	"To get this item, you must now get in touch with the donor"	,
'email_paiement_ok_acheteur_message_specifique_livraison'	=>	"	 ",
 'email_mise_vente_objet_sujet' 	=>	"confirmation of delayed payment"	,
'email_paiement_ok_acheteur_message'	=>	"	 ",
'email_rappel_asso_message'	=>	"	 ",
'email_paiement_ok_kidonateur_message_specifique_posteouvenir'	=>	"	 ",
'email_paiement_ok_kidonateur_message_specifique_venir'	=>	"If , meanwhile, you have received your payment, let us know as soon as possible , so that we can release the transaction between the buyer and the seller."	,
'email_paiement_ok_kidonateur_sujet'	=>	"thanks in advance for your participation"	,
'email_paiement_ok_kidonateur_message'	=>	"	 ",
'email_rappel_asso_message'	=>	"	 ",
'email_rappel_asso_sujet'	=>	"confirmation of delayed payment"	,
'email_rappel_acheteur_message'	=>	"	 ",
'email_rappel_acheteur_sujet'	=>	"bought item but delayed payment(first reminder)"	,
'email_rappel_2_acheteur_sujet'	=>	"bought item but delayed payment(second reminder)"	,
'email_rappel_3_acheteur_sujet'	=>	"bought item but delayed payment(third reminder)"	,
'email_rappel_vendeur_message'	=>	"	 ",
'email_rappel_vendeur_sujet'	=>	"Sold item but delayed payment"	,
'email_signature'	=>	"Kidonaki. I new way to make a gift!"	,
'email_suiveur_avis_24_heures_objet_message'	=>	"	 ",
'email_suiveur_avis_24_heures_sujet'	=>	"imminent sale closure. Don't wait"	,
'enchere_cloture'	=>	"The bidding is closed on……………"	,
'encheres'	=>	"Bidding"	,
'encheres_maj'	=>	"	 ",
'enregistrer'	=>	"enter"	,
'erreur_choisir_image'	=>	"Please, select a picture"	,
'erreur_saisie'	=>	"	 ",
'explicatif_ajouter_categorie'	=>	"Star-dotted categories are main categories and can't be selected"	,
'explicatif_montant_maximum'	=>	"(The system will automatically make bidding for you without exceeding this amount)"	,
'explicatif_prix'	=>	"minimum 5 E"	,

//	F		,
'fin'	=>	"end"	,
'fin_enchere_non_termine'	=>	"bidding is not closed"	,
'fin_enchere_termine'	=>	"bidding closed"	,
'fisc'	=>	"	 ",
'formats_autorises'	=>	"only png,gif pictures are allowed"	,

//	I		,
'id_objet'	=>	"ID items"	,
'info_ong_marques'	=>	"Specific information from the association"	,
'infos_marques_asso'	=>	"Information related to the association"	,
'invendu'	=>	"Unsold"	,

//	L		,
'livraison'	=>	"Delivery carried out"	,
'livraison_court'	=>	"delivery"	,
			,
//	M		,
'marque'	=>	"Brand/ firm"	,
'mise_en_vente'	=>	"Putting up for sale"	,
'mise_en_vente_active'	=>	"Active putting up for sale"	,
'email_mise_vente_objet_sujet'	=>	"Confirmed putting up for sale"	,
'mode_livraison'	=>	"Mode of delivery"	,
'montant'	=>	"	 ",
'montant_trop_bas'	=>	"The minimum amount is………………"	,
'montant_mise'	=>	"Amount"	,
'montant_mise_maximum'	=>	"maximum amount"	,

//	N		,
'neuf'	=>	"new"	,
'nom_famille_personne_reponsable'	=>	"Family name of the person in charge"	,
'nom_marque'	=>	"Advertised name"	,
'nom_organisme'	=>	"Name of the association"	,
'nombre'	=>	"	 ",
'nombre_valide'	=>	"Please, enter a valid number"	,

//	O		,
'occasion'	=>	"Bargain(à saisir) or Second-hand ( de seonde main!)"	,
'objet'	=>	"item"	,
'ong'	=>	"Association/Non-governmental organisation"	,

//	P		,
'particulier'	=>	"Private individual"	,
'paypal'	=>	"Paypal account"	,
'paypal_explications'	=>	"If you accept paypal payments, please give the e-mail address of your paypal account"	,
'personne_morale'	=>	"Moral person"	,
'personne_physique'	=>	"Physical person"	,
'poste'	=>	"Sent by post"	,
'posteouvenir'	=>	"Taking away at the seller's or post delivery"	,
'prenom_personne_reponsable'	=>	"Christian name of the person in charge"	,
'priorites'	=>	"Mention the projects you want to support"	,
'prix'	=>	"Price"	,
'prix_achat_inmediat'	=>	"Direct sale (fixed price paid by the buyer to the supported project)"	,
'prix_depart'	=>	"Auction( The start price is the minimum price )"	,
'prix_depart_expl'	=>	"Minimum amount paid by the buyer to the supported project"	,
'prix_livraison'	=>	"delivery costs"	,
'prix_livraison_expl'	=>	"(Amount paid by the buyer to the seller. Don't fill in if no delivery)	",
'prix_maximum_trop_bas'	=>	"The maximum amount must be………………."	,
'prix_trop_bas'	=>	"Your amount is lower than 5 E. Please put on sale items the value of which is lower than 5 E."	,
'prix_valide'	=>	"Please, encode a figure only, without symbol"	,
'projet'	=>	"Project"	,
'projet_desactive'	=>	"The present-day project of this item has been deactivated.Please, chose another one."	,

//	R		,
'region'	=>	"District"	,

//	S		,
'section_vendeurs'	=>	"section sellers. (not necessary for buyers)	",
'stand_by'	=>	"To put in stand-by"	,
'statut'	=>	"Status"	,
'statut_asso'	=>	"Status of the association"	,
'statut_juridque'	=>	"Legal status"	,
'supprime'	=>	"Deleted"	,
'supprimer'	=>	"To delete"	,
'supprimer_photo'	=>	"Delete the picture"	,

//	T		,
'taille_document'	=>	"Maximum size : 3 meg."	,
'type'	=>	"State the item is in"	,
'type_auteur'	=>	"Registered as…"	,
'genre_prix'	=>	"Specify the kind of sale"	,

//	V		,
'venir'	=>	"Taking away at the seller's"	,
'vente'	=>	"Sale"	,
'vente_directe'	=>	"This item is on direct sale"	,
'votre_mise'	=>	"Your bid"	,

);

?>